### ISSUE TITLE
安卓10.0可以嘛

### ISSUE THREAD

**Issue by snowhen** [arvinljw/PictureSelector#10]
最新版本支持安卓10.0 拍照和选择照片嘛

**Comment by arvinljw** [comment]
很长时间没有维护了，等之后有时间再升级一版，把视频相关和图片编辑相关的加进去。

**Comment by snowhen** [comment]
可以了，但是需要重新倒入 glide 4.10.0 ,不然会报错




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"arvinljw"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月7日(星期二) 上午10:30
收件人:&nbsp;"arvinljw/PictureSelector"<PictureSelector@noreply.github.com&gt;;
抄送:&nbsp;"1104395285"<1104395285@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [arvinljw/PictureSelector] 安卓10.0可以嘛 (#10)




很长时间没有维护了，等之后有时间再升级一版，把视频相关和图片编辑相关的加进去。
