### ISSUE TITLE
拍照问题

### ISSUE THREAD

**Issue by dahui888** [arvinljw/PictureSelector#12]
点击拍照图片回传不过来,但是相册的能用.相机拍照的功能在红米Note7上无法获取到数据

**Comment by arvinljw** [comment]
解决了，但是我之后的版本是想带着图片编辑功能一起发版，所以就不上传jitpack了。就是拍照的类改了一下就可以了，之前的方式不兼容Android10，不知道为啥我之前测试的那个手机没问题。

**Comment by dahui888** [comment]
> 解决了，但是我之后的版本是想带着图片编辑功能一起发版，所以就不上传jitpack了。就是拍照的类改了一下就可以了，之前的方式不兼容Android10，不知道为啥我之前测试的那个手机没问题。
之前的我用着没问题啊.现在都没问题.只不过我把PNG格式改成JPEG格式了
