### ISSUE TITLE
项目用到这个library 混淆报错

### ISSUE THREAD

**Issue by Kenmmm** [arvinljw/PictureSelector#2]

**Comment by arvinljw** [comment]
不好意思，之前没有提供。。这里提供一下，对于本库中的类目前没有去考虑太多，就先保留所有的吧，其他用到第三方的保持混淆的代码在下边，有重复可以不用加，看看可不可以。
#<该库本身的类的>
-keep class net.arvin.pictureselector.**{ *; }
-keep class com.davemorrissey.labs.subscaleview.**{ * ; }
-keep class uk.co.senab.photoview.**{ *; }

#< Rxjava RxAndroid >
-dontwarn rx.*
-dontwarn sun.misc.**

-keepclassmembers class rx.internal.util.unsafe.*ArrayQueue*Field* {
   long producerIndex;
   long consumerIndex;
}

-keepclassmembers class rx.internal.util.unsafe.BaseLinkedQueueProducerNodeRef {
    rx.internal.util.atomic.LinkedQueueNode producerNode;
}

-keepclassmembers class rx.internal.util.unsafe.BaseLinkedQueueConsumerNodeRef {
    rx.internal.util.atomic.LinkedQueueNode consumerNode;
}
#</Rxjava RxAndroid>

#< glide >
-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public enum com.bumptech.glide.load.resource.bitmap.ImageHeaderParser$** {
  **[] $VALUES;
  public *;
}
#</glide>

#< eventbus 3.0 >
-keepattributes *Annotation*
-keepclassmembers class ** {
    @org.greenrobot.eventbus.Subscribe <methods>;
}
-keep enum org.greenrobot.eventbus.ThreadMode { *; }
-keepclassmembers class * extends org.greenrobot.eventbus.util.ThrowableFailureEvent {
    \<init>(java.lang.Throwable);
}
#</eventbus 3.0>

**Comment by Kenmmm** [comment]
![123](https://user-images.githubusercontent.com/10292984/28600311-d5015eb4-71e3-11e7-8c9f-80803caf56b2.png)
加上之后还是会报错

**Comment by arvinljw** [comment]
没有引入这个库之前你的混淆文件可以使用么？他这是叫你把一些警告去掉。加上这一句试试呢？

-ignorewarning

**Comment by Kenmmm** [comment]
去掉是可以打包的,加上-ignorewarning也是报这个错,日了狗了

**Comment by arvinljw** [comment]
你把你的混淆文件给我看看呢？我这边那样去混淆是可以打包成功的。。我的qq1035407623
