### ISSUE TITLE
Pixel模拟器8.0报错

### ISSUE THREAD

**Issue by Spikoss** [arvinljw/PictureSelector#6]
Caused by: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation

`去掉<activity`
            android:name="net.arvin.selector.uis.SelectorActivity"
            android:screenOrientation="portrait"
            android:theme="@style/TransparentTheme" />
中的android:screenOrientation="portrait"就不出错了

**Comment by arvinljw** [comment]
好的，得空了就适配一下横竖屏显示。

**Comment by arvinljw** [comment]
我试了一下Pixel模拟器8.1，一样的配置，没有报错呢。
